name: hanlearn
description: HanLearn - Smart Mandarin Learning App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  provider: ^6.1.2
  translator: ^1.0.4+1
  lpinyin: ^2.0.3
  percent_indicator: ^4.2.5
  shared_preferences: ^2.5.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/