name: hanlearn
description: HanLearn - Smart Mandarin Learning App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  provider: ^6.1.2
  translator: ^1.0.4+1
  lpinyin: ^2.0.3
  percent_indicator: ^4.2.5
  shared_preferences: ^2.5.4
  google_sign_in: ^7.2.0
  firebase_storage: ^12.0.0
  image_picker: ^1.1.2
  flutter_tts: ^4.2.5
  http: ^1.6.0
  audioplayers: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/HanLearnLogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/HanLearnLogo.png"

